<?php
$brand = $this->getBrand();
$_productCollection = $this->getCollection();
$imagewidth = '200';
$imageheight = '200';
$mode = 'grid';
$image = 'brand_products_content_widget_grid';
$type = 'widget-new-grid';
?>
<h1><?php echo $brand->getName(); ?></h1>

<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_helpertheme = $this->helper('Dckap\Theme\Helper\Data');
$customHelper = $this->helper('DCKAP\Catalog\Helper\Data');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$block1 = $objectManager->create('\Magento\Catalog\Block\Product\ListProduct');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <div class="toolbar toolbar-products">
        <p class="toolbar-amount" id="toolbar-amount">
            <?php if ($block->getLastPageNum() > 1): ?>
                <?php echo __('Items %1-%2 of %3',
                    '<span class="toolbar-number">' . $block->getFirstNum() . '</span>',
                    '<span class="toolbar-number">' . $block->getLastNum() . '</span>',
                    '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
            <?php elseif ($block->getTotalNum() == 1): ?>
                <?php echo __('%1 Item',
                    '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
            <?php else: ?>
                <?php echo __('%1 Items',
                    '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
            <?php endif; ?>
        </p>
        <div class="modes">
            <?php $_modes = $block->getModes(); ?>
            <?php if ($_modes && count($_modes) > 1): ?>
                <strong class="modes-label" id="modes-label"><?= __('View as') ?></strong>
                <?php foreach ($block->getModes() as $_code => $_label): ?>
                    <?php if ($this->getMode() == $_code): ?>
                        <strong title="<?= $_label ?>" class="modes-mode active mode-<?= strtolower($_code) ?>" data-value="<?= strtolower($_code) ?>">
                            <span><?= $_label ?></span>
                        </strong>
                    <?php else: ?>
                        <a class="modes-mode mode-<?= strtolower($_code) ?>" title="<?= $_label ?>" href="?product_list_mode=<?= strtolower($_code) ?>" data-role="mode-switcher" data-value="<?= strtolower($_code) ?>" id="mode-<?= strtolower($_code) ?>" aria-labelledby="modes-label mode-<?= strtolower($_code) ?>">
                            <span><?= $_label ?></span>
                        </a>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
        <?php echo $this->getPagerHtml(); ?>
    </div>
    <?php
    if ($this->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    $pos = $block1->getPositioned();
    ?>
    <?php if ($viewMode == 'grid'): ?>
        <div class="products wrapper <?= $viewMode ?> products-<?= $viewMode ?>">
            <ol class="products list items product-items">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product):
//                    $productSessionData = $customHelper->getSessionProductData($_product->getSku());
                    ?>
                    <li class="item product product-item">
                        <div class="product-item-info" data-container="product-<?= $viewMode ?>">
                            <?php
                            $productImage = $block1->getImage($_product, $imageDisplayArea);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <a href="<?= $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?= $productImage->toHtml() ?>
                            </a>
                            <div class="product details product-item-details">
                                <?php $_productNameStripped = $block1->stripTags($_product->getName(), null, true); ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link" href="<?= $_product->getProductUrl() ?>">
                                        <?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                    </a>
                                </strong>
                                <?= "Product #:" . $_product->getSku(); ?>
                                <?php if ($_product->getTypeInstance()->hasRequiredOptions($_product))
                                    echo "<div class='option-price'></div>";
                                else
                                    echo $block1->getProductPrice($_product); ?>
                                <?= $block1->getReviewsSummaryHtml($_product, $templateType) ?>
                                <?php 
                                $stockConfig = $this->helper('DCKAP\Extension\Helper\Data')->getViewInventoryByLocation();
                            

                                if ($stockConfig != 0) {
                                    ?>
                                    <?php if ($_product->isAvailable()): ?>
                                        <?php //if ($productSessionData['lineItem']['totalAvailable'] > 0): ?>
                                        <div class="stock available"><span><?= __('Available In-Stock') ?></span></div>
                                    <?php else: ?>
                                        <div class="stock unavailable"><span><?= __('Out of stock') ?></span></div>
                                    <?php endif; ?>
                                <?php } ?>
                                <?= $block1->getProductDetailsHtml($_product) ?>

                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                        <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block1->getAddToCartPostParams($_product); ?>
                                                <?php $cartHelper = $this->helper('Magento\Checkout\Helper\Cart'); ?>
                                                <form data-role="tocart-form"
                                                      data-product-sku="<?= $block1->escapeHtml($_product->getSku()) ?>"
                                                      action="<?php echo $cartHelper->getAddUrl($_product); ?>"
                                                      method="post">
                                                    <?php echo $block1->getBlockHtml('formkey') ?>
                                                    <input type="number" name="qty" class="qty" maxlength="12" value="1"
                                                           class="input-text qty form-control"
                                                           data-validate="<?php echo $block1->escapeHtml(json_encode($block1->getQuantityValidators())) ?>"/>

                                                    <button type="submit"
                                                            title="<?= $block1->escapeHtml(__('Add to Cart')) ?>"
                                                            class="action tocart primary">
                                                        <span><?= /* @escapeNotVerified */
                                                            __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <?php if ($showDescription): ?>
                                        <div class="product description product-item-description">
                                            <?= $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                            <a href="<?= $_product->getProductUrl() ?>" title="<?= $_productNameStripped ?>" class="action more"><?= __('Learn More') ?></a>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    <?php else: ?>
        <div class="products wrapper <?= $viewMode ?> products-<?= $viewMode ?>">
            <ol class="products list items product-items">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product):
//                    $productSessionData = $customHelper->getSessionProductData($_product->getSku());
                    ?>
                    <li class="item product product-item">
                        <div class="product-item-info" data-container="product-<?= $viewMode ?>">
                            <?php
                            $productImage = $block1->getImage($_product, $imageDisplayArea);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <a href="<?= $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?= $productImage->toHtml() ?>
                            </a>
                            <div class="product details product-item-details">
                                <div class="product-info-right-section">
                                    <?php
                                    $_productNameStripped = $block1->stripTags($_product->getName(), null, true);
                                    ?>
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link" href="<?= $_product->getProductUrl() ?>">
                                            <?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                        </a>
                                    </strong>
                                    <?= "Product #:" . $_product->getSku(); ?>
                                    <?php echo $block1->getReviewsSummaryHtml($_product, $templateType) ?>
                                    <?php if ($showDescription): ?>
                                        <div class="product description product-item-description">
                                            <?= $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                            <a href="<?= $_product->getProductUrl() ?>" title="<?= $_productNameStripped ?>"
                                               class="action more"><?= __('Learn More') ?></a>
                                        </div>
                                    <?php endif; ?>
                                </div>
                                <div class="product-info-left-section">
                                    <?php if ($_product->getTypeInstance()->hasRequiredOptions($_product))
                                        echo "<div class='option-price'></div>";
                                    else
                                        echo $block1->getProductPrice($_product); ?>
                                    <?= $block1->getProductDetailsHtml($_product) ?>
                                    <div class="product-item-inner">
                                        <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                            <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                                <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block1->getAddToCartPostParams($_product); ?>
                                                <?php $cartHelper = $this->helper('Magento\Checkout\Helper\Cart'); ?>
                                                <form data-role="tocart-form" data-product-sku="<?= $block1->escapeHtml($_product->getSku()) ?>" action="<?php echo $cartHelper->getAddUrl($_product); ?>" method="post">
                                                    <?php echo $block1->getBlockHtml('formkey') ?>
                                                    <input type="number" name="qty" maxlength="12" value="1" class="input-text qty form-control" data-validate="<?php echo $block1->escapeHtml(json_encode($block1->getQuantityValidators())) ?>"/>
                                                    <button type="submit" title="<?= $block1->escapeHtml(__('Add to Cart')) ?>" class="action tocart primary">
                                                        <span><?= __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
                                                <?php $stockConfig = $this->helper('DCKAP\Extension\Helper\Data')->getViewInventoryByLocation();
                                            
                                                        if ($stockConfig != 0 ) {
                                                     ?>
                                                <?php if ($_product->isAvailable()): ?>
                                                    <?php //if ($productSessionData['lineItem']['totalAvailable'] > 0): ?>
                                                    <div class="stock available"><span><?= __('Available In-Stock') ?></span></div>
                                                <?php else: ?>
                                                <div class="stock unavailable"><span><?= __('Out of stock') ?></span></div>
                                            </div>
                                            <?php endif; ?>
                                            <?php } ?>
                                            <?php else: ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    <?php endif; ?>

    <div class="toolbar toolbar-products">
        <p class="toolbar-amount" id="toolbar-amount">
            <?php if ($block->getLastPageNum() > 1): ?>
                <?php echo __('Items %1-%2 of %3',
                    '<span class="toolbar-number">' . $block->getFirstNum() . '</span>',
                    '<span class="toolbar-number">' . $block->getLastNum() . '</span>',
                    '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
            <?php elseif ($block->getTotalNum() == 1): ?>
                <?php echo __('%1 Item',
                    '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
            <?php else: ?>
                <?php echo __('%1 Items',
                    '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
            <?php endif; ?>
        </p>
        <?php echo $this->getPagerHtml(); ?>
    </div>
    <?php if (!$block1->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */
            $_product->getSku() ?>"
                }
            }
        }

        </script>
    <?php endif; ?>
<?php endif; ?>
