<?php
/**
 * Cayan Payments
 *
 * @package Cayan\Payment
 * @author Igor Miura
 * @author Joseph Leedy
 * @copyright Copyright (c) 2018 Cayan (https://cayan.com/)
 * @license https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 */
/** @var \Cayan\Payment\Block\Adminhtml\Order\Item\Discount\Refund $block */
?>
<?php $_source  = $block->getSource() ?>
<?php $block->setPriceDataObject($_source) ?>

<?php if ($block->getRefundedAmount() > 0): ?>
    <tr>
        <td class="label"><?= __('Gift Card Refunded (%1)', $block->getCodesLabel()) ?></td>
        <td><?= $block->getAmountFormatted() ?></td>
    </tr>
<?php endif; ?>
