<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Review\Block\Product\Review $block */
?>
<?php $dckapHelper = $this->helper('DCKAP\Extension\Helper\Data');
$themeHelper = $this->helper('Dckap\Theme\Helper\Data');
$displayReview = $dckapHelper->getDisplayReviews(); 
$checkMode = $themeHelper->getWebsiteMode();?>
<?php if (($displayReview&& $checkMode=="b2b")|| $checkMode=="b2c"){ ?>
<div class="data item title active" data-role="collapsible" id="tab-label-reviews" role="tab" data-collapsible="true" aria-controls="reviews" aria-selected="true" aria-expanded="true" tabindex="0">
    <a class="data switch" tabindex="-1" data-toggle="trigger" href="#reviews" id="tab-label-reviews-title"><span class="counter"></span> Product Reviews </a>
</div>
<div class="data item content" aria-labelledby="tab-label-reviews" id="reviews" data-role="content" role="tabpanel" aria-hidden="false">
        <div id="product-review-container" data-role="product-review"></div>

    <?= $block->getChildHtml() ?>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?= $block->escapeJs($block->escapeUrl($block->getProductReviewUrl())) ?>",
                "reviewsTabSelector": "#tab-label-reviews"
            }
        }
    }
</script>
<?php } ?>
