<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Coupons
 */
?>
<?php /** @var Magento\Framework\View\Element\Template $block */ ?>
<script>
    window.checkoutConfig = <?= /* @noEscape */ $block->getCheckoutConfig()->getJsonConfig(); ?>;
    // Create aliases for customer.js model from customer module
    window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
    window.customerData = window.checkoutConfig.customerData;
</script>
