<?php
/** @var Dckap\Theme\Block\UsefulLinks $block */
$links = $block->getFooterUsefulLinks(); ?>
<?php if ($links): ?>
    <div class="footer_links">
        <div class="block">
            <h3><?= __('Useful Links') ?></h3>
            <ul class="useful-links">
                <?php foreach ($links as $link): ?>
                    <li>
                        <a href="<?= $block->getUrl($link['useful_link_href']) ?>" title="<?= $link['useful_link_name'] ?>">
                            <?= ucwords($link['useful_link_name']) ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>

