<?php
$submitUrl = $block->getSubmitUrl();
$helper = $this->helper('Dckap\Attachment\Helper\Data');
$sections = $helper->getPdfSections();
?>
<div class="import-categories">
    <form id="import-form" action="<?= $submitUrl; ?>" method="post" enctype="multipart/form-data">
        <div class="page-main-actions">
            <div class="page-actions-placeholder" style=""></div>
            <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
                <div class="page-actions-inner" data-title="Import">
                    <div class="page-actions-buttons">
                        <button id="upload_button" title="Check Data" type="submit"
                                class="action-default scalable save primary">
                            <span>Import Attachment</span>
                        </button>
                        <a href="<?= $block->getSampleCsvUrl(); ?>" title="Sample csv download" class="action-default scalable save primary" style="line-height: 30px;">
                            <span>Sample CSV</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div><input name="form_key" type="hidden" value="<?= $block->getFormKey() ?>"/></div>
        <fieldset class="fieldset admin__fieldset" style="display: block;">
            <legend class="admin__legend legend">
                <span>File to Import</span>
            </legend>
            <br>
            <div class="messages">
            </div>
            <div class="admin__field field field-attachment  required _required">
                <label class="label admin__field-label" for="attachment">
                    <span>Select File to Import</span>
                </label>
                <div class="admin__field-control control">
                    <input id="attachment" name="attachment" value="" title="Select File to Import" class="attachment required-entry _required" type="file" aria-required="true" />
                </div>
            </div>
            <div class="admin__field field field-type required _required with-note">
                <label class="label admin__field-label" for="type"><span>Select Type</span></label>
                <div class="admin__field-control control">
                    <select id="type" name="type" title="Select Type" class="type required-entry _required select admin__control-select" aria-required="true">
                        <option value="">-- Please Select --</option>
                        <option value="1">Add as New</option>
                        <option value="2">Update</option>
                    </select>
                    <div class="note admin__field-note" id="type-note"></div>
                </div>
            </div>
            <div class="admin__field field field-import_attachment_dir  with-note">
                <label class="label admin__field-label" for="import_attachment_dir">
                    <span>Attachment File Directory</span>
                </label>
                <div class="admin__field-control control">
                    <input id="import_attachment_dir" name="import_attachment_dir" value="" title="Images File Directory" class="import_attachment_dir input-text admin__control-text" type="text">
                    <div class="note admin__field-note" id="import_attachment_dir-note">For Type "Local Server" use relative path to Magento installation, e.g. var/export, var/import, var/export/some/dir
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</div>