<?php $permission = $block->isDisplayed();
//$permission = true;
$params = $this->getRequest()->getParams();
if ($permission) {
    $orderList = $block->getDdiOrders();
    $orderHandle = $block->getHandle();
    $sortArray = array(
        'orderNumber' => 'Order #',
        'orderTotal' => 'Order Total'
    );
    $array_startdate = explode('/',$orderHandle['start_date']);
    $array_enddate = explode('/',$orderHandle['end_date']);
    if(!checkdate($array_startdate[0],$array_startdate[1],$array_startdate[2])){
        $error = 1;
        $error_msg = "Invalid start date.";
    }elseif (!checkdate($array_enddate[0],$array_enddate[1],$array_enddate[2])){
        $error = 1;
        $error_msg = "Invalid end date.";
    }
    ?>
    <div id="message-error" style="display: none;"></div>

    <div class="row toolbar invoice-actions top">
        <div class="col-md-12 col-sm-12">
            <div class="start_date-filter">
                <label for="start_date">Start Date</label>
                <input type="text" class="start_date date hasDatepicker" name="start_date" value="<?php echo $orderHandle['start_date']; ?>" />
            </div>
            <div class="end_date-filter">
                <label for="end_date">End Date</label>
                <input type="text" class="end_date date hasDatepicker" name="end_date" value="<?php echo $orderHandle['end_date']; ?>" />
            </div>
            <a class="btn btn-default search-by-date" href="#" title="Filter by Date">Search</a>
        </div>
        <div class="toolbar-sorter sorter">
            <label class="sorter-label" for="sorter">Sort By</label>
            <select id="sorter" data-role="sorter" class="sorter-options">
                <option value="">select</option>
                <?php foreach ($sortArray as $key => $val) { ?>
                    <option value="<?php echo $key; ?>" <?php if ($key == $orderHandle['current_sfield']) { echo 'selected="selected"'; } ?>><?php echo $val; ?></option>
                <?php } ?>
            </select>
            <?php if ($orderHandle['current_sorder'] == 1) { ?>
                <a title="Set Descending Direction" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc" style="display: block;">
                    <span>Set Descending Direction</span>
                </a>
            <?php } else { ?>
                <a title="Set Ascending Direction" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc" style="display: block;">
                    <span>Set Ascending Direction</span>
                </a>
            <?php } ?>
        </div>
    </div>
    <?php
    if(!empty($error)){ ?>
        <div class="message info empty"><span><?= $error_msg; ?></span></div>
   <?php }else{
    if (count($orderList)):
        $viewUrl = $block->getUrl('quickrfq/order/view');
    ?>

    <div class="row toolbar order-history-actions top">
        <div class="pager">
            <p class="toolbar-amount">
                <span class="toolbar-number">Items <?php echo isset($orderHandle['start']) ?  $orderHandle['start'] :  '1' ?> to <?php echo isset($orderHandle['end']) ?  $orderHandle['end'] :  '25' ?> of <?php echo isset($orderHandle['records_count']) ?  $orderHandle['records_count'] :  '' ?> total</span>
            </p>
        </div>
    </div>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-pad order-list-table" id="my-orders-table">
            <caption class="table-caption"><?= __('Order List') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col order-number"><?= __('Order #') ?></th>
                <th scope="col" class="col po-number"><?= __('PO #') ?></th>
                <th scope="col" class="col order-date"><?= __('Date') ?></th>
                <th scope="col" class="col ship-date"><?= __('Ship Date') ?></th>
                <th scope="col" class="col order-total"><?= __('Order Total') ?></th>
                <th scope="col" class="col status"><?= __('Order Status') ?></th>
                <th scope="col" class="col actions"><?= __('Action') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($orderList as $item): ?>
                <tr class="content">
                    <td data-th="Order #" class="col order-number"><?php echo $item['orderNumber']; ?></td>
                    <td data-th="PO #" class="col po-number"><?php echo $item['poNum']; ?></td>
                    <td data-th="Date" class="col order-date"><?php echo $item['orderDate']; ?></td>
                    <td data-th="Ship Date" class="col ship-date"><?php echo $item['shipDate']; ?></td>
                    <td data-th="Order Total" class="col order-total"><?php echo $item['orderTotal']; ?></td>
                    <td data-th="Order Status" class="col status"><?php echo $item['orderStatus']; ?></td>
                    <td data-th="Action" class="col actions"><a href="<?php echo $viewUrl.'id/'.$item['orderNumber']; ?>" title="View Order" class="action view"><span>View Order</span></a></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="order-products-toolbar toolbar top">
        <div class="pager">
            <div class="pages">
                <strong class="label pages-label" id="paging-label">Page</strong>
                <ul class="items pages-items" aria-labelledby="paging-label">
                    <?php $url = '';
                    if (isset($params['sfield'])) {
                        $url = 'sfield='.$params['sfield'];
                        if (isset($params['sorder'])) {
                            $url .= '&sorder='.$params['sorder'];
                        }
                    } ?>
                    <!--<li class="item">
                        <?php /*$href = '#';
                        if (isset($orderHandle['shipto']) && isset($orderHandle['first_page'])) {
                            $href = '?shipto='.$orderHandle['shipto'].'&page=' . $orderHandle['first_page'];
                        } elseif (!(isset($orderHandle['shipto'])) && isset($orderHandle['first_page'])) {
                            $href = '?page=' . $orderHandle['first_page'];
                        } elseif (isset($orderHandle['shipto']) && !(isset($orderHandle['first_page']))) {
                            $href = '?shipto=' . $orderHandle['shipto'];
                        } */?>
                        <a href="<?php /*echo $href; */?>" class="page">
                            <span class="label">Page</span>
                            <span>First Page</span>
                        </a>
                    </li>-->
                    <li class="item pages-item-previous">
                        <?php $href = '#';
                        if (isset($orderHandle['prev_page'])) {
                            $href = '?page=' . $orderHandle['prev_page'].'&startDate='.$orderHandle['start_date'].'&endDate='.$orderHandle['end_date'];
                            if ($url != '') {
                                $href .= '&'.$url;
                            }
                        } ?>
                        <a class="action  previous" href="<?php echo $href; ?>" title="Previous">
                            <span class="label">Page</span>
                            <span>Previous</span>
                        </a>
                    </li>
                    <li class="item pages-item-next">
                        <?php $href = '#';
                        if (isset($orderHandle['next_page'])) {
                            $href = '?page=' . $orderHandle['next_page'].'&startDate='.$orderHandle['start_date'].'&endDate='.$orderHandle['end_date'];
                            if ($url != '') {
                                $href .= '&'.$url;
                            }
                        } ?>
                        <a class="action  next" href="<?php echo $href; ?>" title="Next">
                            <span class="label">Page</span>
                            <span>Next</span>
                        </a>
                    </li>
                    <!--<li class="item">
                        <?php /*$href = '#';
                        if (isset($orderHandle['shipto']) && isset($orderHandle['last_page'])) {
                            $href = '?shipto='.$orderHandle['shipto'].'&page=' . $orderHandle['last_page'];
                        } elseif (!(isset($orderHandle['shipto'])) && isset($orderHandle['last_page'])) {
                            $href = '?page=' . $orderHandle['last_page'];
                        } elseif (isset($orderHandle['shipto']) && !(isset($orderHandle['last_page']))) {
                            $href = '?shipto=' . $orderHandle['shipto'];
                        } */?>
                        <a href="<?php /*echo $href; */?>" class="page">
                            <span class="label">Page</span>
                            <span>Last Page</span>
                        </a>
                    </li>-->
                </ul>
            </div>
        </div>
    </div>
<?php else: ?>
    <div class="message info empty"><span><?= __('You have no orders at this time.') ?></span></div>
<?php endif ?>
<?php }} else { ?>
    <div class="message info"><span><?= __("You don't have permission to access this page.") ?></span></div>
<?php } ?>
<script>
    require([
        'jquery',
        'mage/mage',
        'mage/calendar'
    ], function($){
        $('.date').datepicker({
            dateFormat: 'mm/dd/y',
            changeMonth: true,
            changeYear: true
        });

        /* date by filter */
        $(document).on("click", "a.search-by-date", function (e) {
            var val = $(this).val();
            if ($(".start_date").val() != '' && $(".end_date").val() != '') {
                var url = '<?php echo $block->getUrl("quickrfq/order/history/"); ?>';
                var startDate = '';
                var endDate = '';
                if ($(".start_date").val() != '') {
                    startDate = $(".start_date").val();
                }
                if ($(".end_date").val() != '') {
                    endDate = $(".end_date").val();
                }
                url += '?startDate='+startDate+'&endDate='+endDate;
                var hash;
                var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
                for(var i = 0; i < hashes.length; i++)
                {
                    hash = hashes[i].split('=');
                    if(hash[0]== "sfield" || hash[0]== "sorder"){
                        url +='&'+hash[0]+'='+hash[1];
                    }
                }
                window.location.href = url;
            } else {
                alert('Please select date fields to proceed.');
            }
        });

        /* sort-by selection */
        $(document).on("change", "#sorter", function (e) {
            var val = $(this).val();
            var url = '<?php echo $block->getUrl("quickrfq/order/history/"); ?>';
            url += '?sfield='+val;
            var hash;
            var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
            for(var i = 0; i < hashes.length; i++)
            {
                hash = hashes[i].split('=');
                if(hash[0]== "startDate" || hash[0]== "endDate"){
                    url +='&'+hash[0]+'='+hash[1];
                }
            }
            window.location.href = url;
        });
        $(document).on("click", ".sort-desc", function (e) {
            e.preventDefault();
            var url = '<?php echo $block->getUrl("quickrfq/order/history/"); ?>';
            var sfield = '';
            if ($("#sorter").val() != '') {
                sfield = $("#sorter").val();
            } else {
                return false;
            }
            url += '?sfield='+sfield+'&sorder=1';
            var hash;
            var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
            for(var i = 0; i < hashes.length; i++)
            {
                hash = hashes[i].split('=');
                if(hash[0]== "startDate" || hash[0]== "endDate"){
                    url +='&'+hash[0]+'='+hash[1];
                }
            }
            window.location.href = url;
        });
        $(document).on("click", ".sort-asc", function (e) {
            e.preventDefault();
            var url = '<?php echo $block->getUrl("quickrfq/order/history/"); ?>';
            var sfield = '';
            if ($("#sorter").val() != '') {
                sfield = $("#sorter").val();
            } else {
                return false;
            }
            url += '?sfield='+sfield+'&sorder=0';
            var hash;
            var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
            for(var i = 0; i < hashes.length; i++)
            {
                hash = hashes[i].split('=');
                if(hash[0]== "startDate" || hash[0]== "endDate"){
                    url +='&'+hash[0]+'='+hash[1];
                }
            }
            window.location.href = url;
        });
    });
</script>
