<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */

$_helperoption = $this->helper('DCKAP\Catalog\Helper\Data');
$mobileLogo=$_helperoption->getConfig('mobile_logo/general/upload_image_id');
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<span data-action="toggle-nav" class="action nav-toggle"><span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span></span>
<?php if ($block->isHomePage()):?>
    <strong class="logo">
<?php else: ?>
    <a class="logo" href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
<?php endif ?>
        <img class="desktop-logo" src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
             title="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
             alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
             <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
             <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        />
        <?php 
            if($mobileLogo)
            echo '<img class="mobile-logo" src="'.$_helperoption->getMediaUrl().'/logo/mobile/'.$mobileLogo.'">';?>

<?php if ($block->isHomePage()):?>
    </strong>
<?php else:?>
    </a>
<?php endif?>
