<?php $order = $block->getDdiQuote();
if ($order && count($order) && $order['isValid'] == 'yes'): ?>
    <div class="page-title-wrapper">
        <h1 class="page-title">
            <span class="base" data-ui-id="page-title-wrapper">Quote # <?php echo $order['orderNumber']; ?></span></h1>
        <span class="order-status"><?php echo $order['orderDetails']['orderStatus']; ?></span>
        <div class="order-date">
            <span class="label">Quote Date:</span>
            <date><?php echo $order['orderDetails']['orderDate']; ?></date>
        </div>
    </div>
    <div class="actions-toolbar order-actions-toolbar">
        <div class="actions" data-mage-init='{"addToCartPopup": {}}' >
            <div id="add-to-cart-popup" style="display: none">
                <div class="actions-toolbar">
                    <div>
                        <strong>ALERT: </strong><span>Selecting to continue will remove all products from your cart and replace with selected quote.</span>
                    </div>
                    <div class="add-to-cart secondary"><button class=""><?= __('Continue') ?></button></div>
                    <div>
                        <span>Review your cart if you wish to save the current products.</span>
                    </div>
                    <div class="primary"><button class="go-to-cart"><?= __('Go To Cart') ?></button></div>
                </div>
                <input type="hidden" class="ddiOrderId" value="" />
            </div>

            <a class="action print" href="<?php echo $block->getUrl('quickrfq/quote/printview/').'id/'.$order['orderNumber']; ?>" onclick="this.target='_blank';" title="Print Quote">
                <span>Print Quote</span>
            </a>
            <a href="#" title="Place Order" class="action view place-order" id=<?=$order['orderNumber']?>><span>Place Order</span></a>
        </div>
    </div>
    <ul class="items order-links">
        <li class="nav item current"><strong>Items Quoted</strong></li>
    </ul>
    <div class="order-details-items ordered">
        <div class="order-title">
            <strong>Items Quoted</strong>
        </div>
        <div class="table-wrapper order-items">
            <table class="data table table-order-items" id="my-orders-table" summary="Items Ordered">
                <caption class="table-caption">Items Quoted</caption>
                <thead>
                <tr>
                    <th class="col name">Product Name</th>
                    <th class="col sku">SKU</th>
                    <th class="col price">Price</th>
                    <th class="col qty">Qty</th>
                    <th class="col subtotal">Subtotal</th>
                </tr>
                </thead>
                <tbody>
                <?php if (isset($order['lineItems']['lineData']) && count($order['lineItems']['lineData'])) {
                  foreach ($order['lineItems']['lineData'] as $item) {
                    ?>
                      <tr id="order-item-row-32">
                          <td class="col name" data-th="Product Name">
                              <strong class="product name product-item-name"><?php echo $item['description']; ?></strong>
                          </td>
                          <td class="col sku" data-th="SKU"><?php echo $item['stockNum']; ?></td>
                          <td class="col price" data-th="Price">
                                <span class="price-excluding-tax" data-label="Excl. Tax">
                                    <span class="cart-price">
                                        <span class="price"><?php echo $item['netPrice']; ?></span>
                                    </span>
                                </span>
                          </td>
                          <td class="col qty" data-th="Qty">
                              <span class="content"><?php echo $item['qty']; ?></span>
                          </td>
                          <td class="col subtotal" data-th="Subtotal">
                                <span class="price-excluding-tax" data-label="Excl. Tax">
                                    <span class="cart-price">
                                        <span class="price"><?php echo $item['extendedPrice']; ?></span>
                                    </span>
                                </span>
                          </td>
                      </tr>
                  <?php }
                } ?>
                </tbody>
                <tfoot>
                <tr class="subtotal">
                    <th colspan="4" class="mark" scope="row">Subtotal</th>
                    <td class="amount" data-th="Subtotal"><span class="price"><?php if (isset($order['orderDetails']['merchandiseTotal']) && $order['orderDetails']['merchandiseTotal'] != '') {
                          echo $order['orderDetails']['merchandiseTotal'];
                        } else {
                          echo '$0.00';
                        } ?></span></td>
                </tr>
                <tr class="misctotal">
                    <th colspan="4" class="mark" scope="row">Miscellaneous Total</th>
                    <td class="amount" data-th="Miscellaneous Total"><span class="price"><?php if (isset($order['orderDetails']['miscellaneousTotal']) && $order['orderDetails']['miscellaneousTotal'] != '') {
                          echo $order['orderDetails']['miscellaneousTotal'];
                        } else {
                          echo '$0.00';
                        } ?></span></td>
                </tr>
                <tr class="shipping">
                    <th colspan="4" class="mark" scope="row">Shipping & Handling</th>
                    <td class="amount" data-th="Shipping & Handling">
                        <span class="price"><?php if (isset($order['orderDetails']['freightTotal']) && $order['orderDetails']['freightTotal'] != '') {
                            echo $order['orderDetails']['freightTotal'];
                          } else {
                            echo '$0.00';
                          } ?></span></td>
                </tr>
                <tr class="tax">
                    <th colspan="4" class="mark" scope="row">Tax</th>
                    <td class="amount" data-th="Tax">
                        <span class="price"><?php if (isset($order['orderDetails']['taxTotal']) && $order['orderDetails']['taxTotal'] != '') {
                            echo $order['orderDetails']['taxTotal'];
                          } else {
                            echo '$0.00';
                          } ?></span></td>
                </tr>
                <tr class="grand_total">
                    <th colspan="4" class="mark" scope="row">
                        <strong>Grand Total</strong>
                    </th>
                    <td class="amount" data-th="Grand Total">
                        <strong><span class="price"><?php echo $order['orderDetails']['orderTotal']; ?></span></strong>
                    </td>
                </tr>
                </tfoot>
            </table>
        </div>
        <div class="actions-toolbar">
            <div class="secondary">
                <a class="action back" href="">
                    <span>Back to My Orders</span>
                </a>
            </div>
        </div>
    </div>
    <div class="block block-order-details-view">
        <div class="block-title">
            <strong>Order Information</strong>
        </div>
        <div class="block-content">
            <div class="box box-order-shipping-address">
                <strong class="box-title"><span>Shipping Address</span></strong>
                <div class="box-content">
                    <address><?php echo $order['shipAddress']['shipCompanyName']; ?><br>
                      <?php echo $order['shipAddress']['shipAddress1']; ?><br>
                      <?php echo $order['shipAddress']['shipCity'];
                      if (isset($order['shipAddress']['shipState']) && $order['shipAddress']['shipState'] != '') {
                        echo ', ' . $order['shipAddress']['shipState'];
                      }
                      if (isset($order['shipAddress']['shipPostCode']) && $order['shipAddress']['shipPostCode'] != '') {
                        echo ', ' . $order['shipAddress']['shipPostCode'];
                      } ?>
                      <?php if (isset($order['shipAddress']['shipPhone'])) { ?><br>
                          T: <a href="tel:<?php echo $order['shipAddress']['shipPhone']; ?>"><?php echo $order['shipAddress']['shipPhone']; ?></a>
                      <?php } ?>
                    </address>
                </div>
            </div>
            <div class="box box-order-shipping-method">
                <strong class="box-title">
                    <span>Shipping Method</span>
                </strong>
                <div class="box-content">
                  <?php echo $order['orderDetails']['shipMethod']['shipVia']; ?>
                    - <?php echo $order['orderDetails']['shipMethod']['shipViaDescription']; ?>                                        </div>
            </div>
            <div class="box box-order-billing-address">
                <strong class="box-title">
                    <span>Billing Address</span>
                </strong>
                <div class="box-content">
                    <address><?php echo $order['billAddress']['billCompanyName']; ?><br>
                      <?php echo $order['billAddress']['billAddress1']; ?><br>
                      <?php echo $order['billAddress']['billCity'];
                      if (isset($order['billAddress']['billState']) && $order['billAddress']['billState'] != '') {
                        echo ', ' . $order['billAddress']['billState'];
                      }
                      if (isset($order['billAddress']['billPostCode']) && $order['billAddress']['billPostCode'] != '') {
                        echo ', ' . $order['billAddress']['billPostCode'];
                      } ?>
                      <?php if (isset($order['billAddress']['billPhone'])) { ?><br>
                          T: <a href="tel:<?php echo $order['billAddress']['billPhone']; ?>"><?php echo $order['billAddress']['billPhone']; ?></a>
                      <?php } ?>
                    </address>
                </div>
            </div>
        </div>
      <?php if (isset($order['orderDetails']['poNum']) && $order['orderDetails']['poNum'] != '') { ?>
          <div class="block-content">
              <div class="box box-order-shipping-address">
                  <strong class="box-title"><span>PO Number</span></strong>
                  <div class="box-content">
                      <p>
                        <?= $order['orderDetails']['poNum'] ?>
                      </p>
                  </div>
              </div>
          </div>
      <?php } ?>
    </div>
<?php else: ?>
    <div class="message info empty"><span><?= __('Quote detail not found.') ?></span></div>
<?php endif ?>
<script type="text/javascript">
    require([
        'jquery',
        'mage/mage'
    ], function($){
        $(document).on("click", ".truncate_cart", function (e) {

            var val = $(this).attr('id');
            // alert(val);
            // var cartData = customerData.get('cart');
            $.ajax({
                url: '<?php echo $this->getUrl('quickrfq/quote/order');?>',
                type: 'POST',
                data:{'id':val},
                showLoader: true ,
                success: function (res) {
                    console.log(res.msg);
                    if(res.msg){

                        window.location.href = '<?php echo $this->getUrl('checkout/cart/updatePost/');?>';
                        return true;
                    }else{
                        alert("Something went wrong.please try again!")
                    }
                }
            });
        });
    });
</script>