<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */

$_productCollection = $block->getLoadedProductCollection();

if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= /* @escapeNotVerified */
            __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else:
    $defaultUom = "EA";
    $stock = 0;
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $customHelper = $this->helper('DCKAP\Catalog\Helper\Data');
    $checklogin = $customHelper->checkloggedin();
    $cartHelper = $this->helper('Magento\Checkout\Helper\Cart');
    $extensionHelper = $this->helper('DCKAP\Extension\Helper\Data');
    $stockConfig = $extensionHelper->getViewInventoryByLocation();
    $guestStockConfig = $extensionHelper->getGuestStockDisplay();
    ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    if ($viewMode == 'grid'): ?>
        <div class="products wrapper <?= $viewMode ?> products-<?= $viewMode ?>">
            <ol class="products list items product-items">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product):
                    $offline = $_product->getData('offline'); ?>
                    <li class="item product product-item <?php if ($_product->getTypeId() == 'configurable') { echo 'configurable'; } ?>">
                        <div class="product-item-info" data-container="product-<?= $viewMode ?>" id="product-id-<?php echo $_product->getId(); ?>"
                             <?php if (!($_product->getTypeId() == 'configurable' || $_product->getTypeId() == 'grouped')) { ?>data-product-id="<?php echo $_product->getId(); ?>" <?php } ?>>
                            <?php $productImage = $block->getImage($_product, $imageDisplayArea);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            } ?>
                            <a href="<?= $_product->getProductUrl(); ?>" class="product photo product-item-photo" tabindex="-1">
                                <?= $productImage->toHtml(); ?>
                            </a>
                            <div class="product details product-item-details">
                                <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link" title="<?= $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>" href="<?= $_product->getProductUrl(); ?>">
                                        <?= $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </strong>
                                <div class="product-sku-txt">
                                    <?php echo 'Product #:' . $_product->getSku(); ?>
                                </div>
                                <?php if (!$offline || $offline == "0") {
                                    if ($_product->getTypeId() == 'configurable' || $_product->getTypeId() == 'grouped') { ?>
                                        <a href="<?= $_product->getProductUrl() ?>" title="<?= $_productNameStripped ?>" class="button action"><?= __('Choose an Option') ?></a>
                                    <?php } else {
                                        if ($_product->isSaleable()) { ?>
                                            <?= $block->getProductPrice($_product); ?>
                                        <?php } ?>
                                        <?= $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                        <?php if ($customHelper->getStockDisplay() > 0) {
                                            if ($stock > 0) { ?>
                                                <div class="stock available">
                                                    <span><?= __('Available In-Stock') ?></span></div>
                                            <?php } else { ?>
                                                <div class="stock unavailable">
                                                    <span><?= __('Out of stock') ?></span>
                                                </div>
                                            <?php }
                                        } ?>
                                        <?= $block->getProductDetailsHtml($_product); ?>
                                        <div class="product-item-inner">
                                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                                    <?php if ($_product->isSaleable()) { ?>
                                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?php echo $cartHelper->getAddUrl($_product); ?>" method="post">
                                                            <?php echo $block->getBlockHtml('formkey'); ?>
                                                            <input type="number" name="qty" class="qty" maxlength="12" value="1" min="1" required class="input-text qty form-control" data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())); ?>"/>
                                                            <input type="hidden" name="custom_uom" class="custom_uom" value="<?= $defaultUom; ?>"/>
                                                            <button type="submit" title="<?= $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary">
                                                                <span><?= __('Add to Cart') ?></span>
                                                            </button>
                                                        </form>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                        </div>
                                    <?php }
                                } ?>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    <?php else: ?>
        <div class="products wrapper <?= $viewMode ?> products-<?= $viewMode ?>">
            <ol class="products list items product-items">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product):
                    $offline = $_product->getData('offline'); ?>
                    <li class="item product product-item <?php if ($_product->getTypeId() == 'configurable') { echo 'configurable'; } ?>">
                        <div class="product-item-info" data-container="product-<?= $viewMode ?>" id="product-id-<?php echo $_product->getId(); ?>"
                             <?php if (!($_product->getTypeId() == 'configurable' || $_product->getTypeId() == 'grouped')) { ?>data-product-id="<?php echo $_product->getId(); ?>" <?php } ?>>
                            <?php $productImage = $block->getImage($_product, $imageDisplayArea);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            } ?>
                            <a href="<?= $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?= $productImage->toHtml(); ?>
                            </a>
                            <div class="product details product-item-details">
                                <div class="product-info-right-section">
                                    <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link" href="<?= $_product->getProductUrl() ?>">
                                            <?= $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </strong>
                                    <?= "Product #:" . $_product->getSku(); ?>
                                    <?= $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                    <?php if ($showDescription) { ?>
                                        <div class="product description product-item-description">
                                            <?= $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'); ?>
                                            <a href="<?= $_product->getProductUrl() ?>" title="<?= $_productNameStripped ?>" class="action more"><?= __('Learn More') ?></a>
                                        </div>
                                    <?php } ?>
                                </div>
                                <div class="product-info-left-section">
                                    <?php if (!$offline || $offline == "0") {
                                        if ($_product->getTypeId() == 'configurable' || $_product->getTypeId() == 'grouped') { ?>
                                            <a href="<?= $_product->getProductUrl() ?>" title="<?= $_productNameStripped ?>" class="button action"><?= __('Choose an Option') ?></a>
                                        <?php } else { ?>
                                            <?= $block->getProductDetailsHtml($_product); ?>
                                            <?php if ($_product->isSaleable()) { ?>
                                                <?= $block->getProductPrice($_product); ?>
                                            <?php } ?>
                                            <div class="product-item-inner">
                                                <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                                    <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                                        <?php if ($_product->isSaleable()) { ?>
                                                            <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?php echo $cartHelper->getAddUrl($_product); ?>" method="post">
                                                                <?php echo $block->getBlockHtml('formkey'); ?>
                                                                <input type="number" name="qty" class="qty" maxlength="12" value="1" min="1" required class="input-text qty form-control" data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())); ?>"/>
                                                                <input type="hidden" name="custom_uom" class="custom_uom" value="<?= $defaultUom; ?>"/>
                                                                <button type="submit" title="<?= $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary">
                                                                    <span><?= __('Add to Cart') ?></span>
                                                                </button>
                                                            </form>
                                                        <?php } ?>
                                                        <?php if ($customHelper->getStockDisplay() > 0) {
                                                            if ($stock > 0) { ?>
                                                                <div class="stock available">
                                                                    <span><?= __('Available In-Stock') ?></span></div>
                                                            <?php } else { ?>
                                                                <div class="stock unavailable">
                                                                    <span><?= __('Out of stock') ?></span></div>
                                                            <?php }
                                                        } ?>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php }
                                    } ?>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    <?php endif; ?>
    <?= $block->getToolbarHtml(); ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
                "[data-role=tocart-form], .form.map.checkout": {
                    "catalogAddToCart": {
                        "product_sku": "<?= /* @NoEscape */
            $_product->getSku() ?>"
                    }
                }
            }
        </script>
    <?php endif; ?>
<?php endif; ?>
