<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 4;
            $shuffle = 0;
//            $canItemsAddToCart = $block->canItemsAddToCart();
            $canItemsAddToCart = false;

            $showAddTo = false;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    default:
        $exist = null;
}
?>
<?php
$extensionHelper = $this->helper('DCKAP\Extension\Helper\Data');
$stockConfig = $extensionHelper->getViewInventoryByLocation();
$guestStockConfig = $extensionHelper->getGuestStockDisplay();

?>
<?php if ($exist):?>

    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
        <?php else: ?>
            <div class="block <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?= /* @escapeNotVerified */ $class ?>">
    <?php endif; ?>
    <div class="block-title title">
        <strong id="block-<?= /* @escapeNotVerified */ $class ?>-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */ $title ?></strong>
    </div>
    <div class="block-content content" aria-labelledby="block-<?= /* @escapeNotVerified */ $class ?>-heading">
        <?php if ($type == 'related' && $canItemsAddToCart): ?>
        <div class="block-actions">
            <?= /* @escapeNotVerified */ __('Check items to add to the cart or') ?>
            <button type="button" class="action select" role="select-all"><span><?= /* @escapeNotVerified */ __('select all') ?></span></button>
        </div>
        <?php endif; ?>
        <div class="products wrapper grid products-grid products-<?= /* @escapeNotVerified */ $type ?>">
            <ol class="products list items product-items">
                 <div id="mp-list-items" class="owl-carousel owl-theme">

                <?php foreach ($items as $_item):
                    $offline = 0;
                    if($offline = $_item->getCustomAttribute('offline')) {
                        $offline = $_item->getData('offline');
                    } ?>
                <?php $available = ''; ?>
                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                    <?php if (!$_item->getRequiredOptions()): ?>
                        <?php $available = 'related-available'; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($type == 'related' || $type == 'upsell'): ?>
                    <li class="item product product-item" style="display: none;">
                <?php else: ?>
                    <li class="item product product-item">
                <?php endif; ?>
                <div class="product-item-info <?php echo $_item->getTypeId(); ?> <?= /* @escapeNotVerified */ $available ?>" id="product-id-<?php echo $_item->getId(); ?>">
                    <?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
                    <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                        <?= $block->getImage($_item, $image)->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name"><a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>">
                            <?= $block->escapeHtml($_item->getName()) ?></a>
                        </strong>
                        <div class="price-outer-container">
                        <?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>
                        </div>
                        <?php if (!$offline || $offline == "0") { ?>
                          <?php if (($guestStockConfig != 0) && ($stockConfig != 0)) {
                             if ($_item->getData('erp_qty') > 0) {  ?>
                            <div class="stock available">
                                <span><?= __('Available In-Stock') ?></span></div>
                            <?php } else { ?>
                                    <div class="stock unavailable">
                                        <span><?= __('Out of stock') ?></span></div>
                                <?php } 
                        } ?>
                        <?php } ?>
                            <?php //if ($templateType): ?>
                        <?php //echo $block->getReviewsSummaryHtml($_item, 'short', true) ?>
                            <?php //endif; ?>
                        
                            <?php if ($showAddTo || $showCart): ?>
                                <div class="product actions product-item-actions">
                                    <?php if ($showCart): ?>
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)):
                                                    if (!$offline || $offline == "0") {
                                                    $cartHelper = $this->helper('Magento\Checkout\Helper\Cart');
                                                    $themeHelper = $this->helper('Dckap\Theme\Helper\Data');
                                                    $defaultUom="EA";
                                                    $uom=$_item->hasData('uom')?$_item->getData('uom'): $defaultUom;
                                                    ?>
                                                    <form action="<?php echo $cartHelper->getAddUrl($_item);?>" method="post" data-role="tocart-form">
                                                        <?php echo $block->getBlockHtml('formkey')?>
                                                        <input type="number" name="qty" minlength="1" maxlength="3" value="1" title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty form-control" />
                                                        <?php
                                                        $customOptions = $themeHelper->getOption()->getProductOptionCollection($_item);
                                                        $optStr = "";
                                                        foreach($customOptions as $optionKey => $optionVal):
                                                            $optStr .= "<div class='custom-options'><label style='display:none;'>".$optionVal->getTitle()." </label>";
                                                            $optStr .= "<select id='select_option' name='options[".$optionVal->getId()."]'>";
                                                            foreach($optionVal->getValues() as $valuesKey => $valuesVal) {
                                                                $optStr .= "<option data-value='".number_format($valuesVal->getPrice(),2)."' value='".$valuesVal->getId()."'>".$valuesVal->getTitle()."</option>";
                                                            }

                                                            $optStr .= "</select></div>";
                                                            echo $optStr;
                                                        endforeach;

                                                        ?>
                                                        <input type="hidden" name="custom_uom" class="custom_uom" value="<?= $uom ?>" />
                                                        <button type="submit" class="submit action tocart primary" title="<?php echo __('Add to Cart') ?>">
                                                            <span><?php echo __('Add to Cart') ?></span>
                                                        </button>
                                                    </form>
                                            <?php } ?>
                                                  <div class="secondary-addto-links actions-secondary"
                                                 data-role="add-to-links">
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                                                        <a href="#"
                                                           data-post='<?= /** @noEscape */ $block->getAddToWishlistParams($_item); ?>'
                                                           class="action towishlist" data-action="add-to-wishlist"
                                                           title="<?= /** @noEscape */ __('Add to Wish List') ?>">
                                                            <span><?= /** @noEscape */ __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                                <?php else: ?>
                                                    <?php
                                                    if (!$offline || $offline == "0") {
                                                    $defaultUom="EA";
                                                    $uom=$_item->hasData('uom')?$_item->getData('uom'): $defaultUom;
                                                    ?>
                                                    <form action="<?php echo $block->getAddToCartUrl($_item);?>" method="post" data-role="tocart-form">
                                                        <?php echo $block->getBlockHtml('formkey')?>
                                                        <input type="number" name="qty" minlength="1" maxlength="12" value="1" title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty form-control" />
                                                        <input type="hidden" name="custom_uom" class="custom_uom" value="<?= $uom ?>" />
                                                        <button type="submit" class="submit action tocart primary" title="<?php echo __('Add to Cart') ?>">
                                                            <span><?php echo __('Add to Cart') ?></span>
                                                        </button>
                                                    </form>
                                                    <?php } ?>
                                                   <div class="secondary-addto-links actions-secondary"
                                                 data-role="add-to-links">
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                                                        <a href="#"
                                                           data-post='<?= /** @noEscape */ $block->getAddToWishlistParams($_item); ?>'
                                                           class="action towishlist" data-action="add-to-wishlist"
                                                           title="<?= /** @noEscape */ __('Add to Wish List') ?>">
                                                            <span><?= /** @noEscape */ __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                                <?php endif; ?>
                                            <?php else: ?>

                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($showAddTo): ?>
                                        <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </li>
                <?php endforeach ?>
            </div>
            </ol>
        </div>
    </div>
</div>
<?php endif;?>
<script type="text/x-magento-init">
{
    "[data-role=tocart-form], .form.map.checkout": {
        "catalogAddToCart": {}
    }
}
</script>

<script>
    require(['jquery', 'jquery/ui'], function($){
        jQuery(document).ready( function() {
            $('.products-related .product-item').css('display','block');
            var price=jQuery('select#select_option').children("option:selected").data('value');
            if(price)
                jQuery('.option-price').html('$'+price);
            jQuery('select#select_option').change(function(){
                var price=jQuery(this).children("option:selected").data('value');
                if(price)
                    jQuery('.option-price').html('$'+price);
            });

        });
    });
</script>
<script>
 require(['jquery', 'mageplaza/core/owl.carousel'], function ($) {
$( document ).ready(function() {
    $('#mp-list-items').owlCarousel(
        {
            loop:false,
            margin:10,
            nav:false,
            responsive:{
                0:{
                    items:1,
                    dots: false,
                },
                600:{
                    items:3,
                    dots: false,
                },
                991:{
                    items:4,
                    dots: false,
                }
            }
        }
    );
});
});
</script>