<?php
$params = $this->getRequest()->getParams();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
/*$cart = $objectManager->get('\Magento\Checkout\Model\Cart');
$quote = $itemsCollection = $cart->getQuote();
$amount = (float)$quote->getGrandTotal();*/
$checkoutSession = $objectManager->get('\Magento\Checkout\Model\SessionFactory')->create();
$checkoutReviewData = $checkoutSession->getCheckoutData();
$amount = $checkoutReviewData['order_total'];
$authorizedAmount = (float)$params['AmountApproved'];
if ($authorizedAmount < $amount) {
    ?>
<script>
    require([
        'jquery',
        'mage/url'
    ], function($, urlBuilder) {
        $(document).ready(function () {
            $('#elementpayment-method #reloadIframe', parent.document).click();
        });
    });
</script>
<?php } else { ?>
<form class="form" id="cc-transaction-result" style="display: none;">
    <fieldset class="fieldset payment items ccard" id="invoice-payment-form">
        <?php if ($params['Status'] == 'User_Cancelled') { ?>
            <div class="field">
                <label class="label">
                    <span>Status</span>
                </label>
                <div class="control">
                    <input type="text" name="status" class="input-text" value="<?php echo $params['Status']; ?>" id="status" readonly />
                </div>
            </div>
            <div class="field">
                <label class="label">
                    <span>ValidationKey</span>
                </label>
                <div class="control">
                    <input type="text" name="validation_key" class="input-text" value="<?php echo $params['ValidationKey']; ?>" id="validation_key" readonly />
                </div>
            </div>
        <?php } else { ?>
        <div class="field">
            <label class="label">
                <span>Status</span>
            </label>
            <div class="control">
                <input type="text" name="status" class="input-text" value="<?php echo $params['Status']; ?>" id="status" readonly />
            </div>
        </div>
        <div class="field">
            <label class="label">
                <span>Card Holder</span>
            </label>
            <div class="control">
                <input type="text" name="cc_holder" class="input-text" value="<?php echo $params['Cardholder']; ?>" id="cc_holder" readonly />
            </div>
        </div>
        <div class="field">
            <label class="label">
                <span>Card Number</span>
            </label>
            <div class="control">
                <input type="text" name="cc_number" class="input-text" value="<?php echo $params['CardNumber']; ?>" id="cc_number" readonly />
            </div>
        </div>
        <div class="field">
            <label class="label">
                <span>Card Type</span>
            </label>
            <div class="control">
                <input type="text" name="cc_type" class="input-text" value="<?php echo $params['CardType']; ?>" id="cc_type" readonly />
            </div>
        </div>
        <div class="field">
            <label class="label">
                <span>AuthCode</span>
            </label>
            <div class="control">
                <input type="text" name="cc_auth_code" class="input-text" value="<?php echo $params['AuthCode']; ?>" id="cc_auth_code" readonly />
            </div>
        </div>
        <div class="field">
            <label class="label">
                <span>Token</span>
            </label>
            <div class="control">
                <input type="text" name="cc_token" class="input-text" value="<?php echo $params['Token']; ?>" id="cc_token" readonly />
            </div>
        </div>
        <div class="field">
            <label class="label">
                <span>ExpDate</span>
            </label>
            <div class="control">
                <input type="text" name="cc_exp_date" class="input-text" value="<?php echo $params['ExpDate']; ?>" id="cc_exp_date" readonly />
            </div>
        </div>
        <div class="field">
            <label class="label">
                <span>ValidationKey</span>
            </label>
            <div class="control">
                <input type="text" name="cc_validation_key" class="input-text" value="<?php echo $params['ValidationKey']; ?>" id="cc_validation_key" readonly />
            </div>
        </div>
        <div class="field">
            <label class="label">
                <span>AmountApproved</span>
            </label>
            <div class="control">
                <input type="text" name="cc_amount_approved" class="input-text" value="<?php echo $params['AmountApproved']; ?>" id="cc_amount_approved" readonly />
            </div>
        </div>
        <?php } ?>
    </fieldset>
</form>
<script>
    require([
        'jquery',
        'mage/url'
    ], function($, urlBuilder) {
        $(document).ready(function () {
            $('#elementpayment-method #getDataFromIframe', parent.document).click();
        });
    });
</script>
<?php } ?>