<?php
$submitUrl = $block->getUrl('productimport/attributeimport/save');
?>
<div class="import-attributes">
    <form id="import-form" action="<?php echo $submitUrl; ?>" method="post" enctype="multipart/form-data">
        <div class="page-main-actions">
            <div class="page-actions-placeholder" style=""></div>
            <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
                <div class="page-actions-inner" data-title="Import">
                    <div class="page-actions-buttons">
                        <button id="upload_button" title="Check Data" type="submit"
                                class="action-default scalable save primary">
                            <span>Import Attributes</span>
                        </button>
                        <a href="<?php echo $block->getSampleCsvUrl(); ?>" title="Sample csv download" class="action-default scalable save primary" style="line-height: 30px;">
                            <span>Sample CSV</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div><input name="form_key" type="hidden" value="<?php echo $block->getFormKey() ?>"/></div>
        <fieldset class="fieldset admin__fieldset" style="display: block;">
            <legend class="admin__legend legend">
                <span>File to Import</span>
            </legend>
            <br>
            <div class="messages">
            </div>
            <div class="admin__field field field-attribute_csv  required _required">
                <label class="label admin__field-label" for="attribute_csv">
                    <span>Select File to Import</span>
                </label>
                <div class="admin__field-control control">
                    <input id="attribute_csv" name="attribute_csv" value="" title="Select File to Import" class="attachment required-entry _required" type="file" aria-required="true" />
                </div>
            </div>
        </fieldset>
    </form>
</div>
<div class="remove-attributes" style="display: none;">
    <form id="import-form" action="<?php echo $block->getUrl('productimport/attributeimport/delete'); ?>" method="post" enctype="multipart/form-data">
        <div class="page-main-actions">
            <div class="page-actions-placeholder" style=""></div>
            <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
                <div class="page-actions-inner" data-title="Import">
                    <div class="page-actions-buttons">
                        <button id="upload_button" title="Check Data" type="submit"
                                class="action-default scalable save primary">
                            <span>Remove Attributes</span>
                        </button>
                        <!--<a href="<?php /*echo $block->getSampleCsvUrl(); */?>" title="Sample csv download" class="action-default scalable save primary" style="line-height: 30px;">
                            <span>Sample CSV</span>
                        </a>-->
                    </div>
                </div>
            </div>
        </div>
        <div><input name="form_key" type="hidden" value="<?php echo $block->getFormKey() ?>"/></div>
        <fieldset class="fieldset admin__fieldset" style="display: block;">
            <legend class="admin__legend legend">
                <span>File to Import</span>
            </legend>
            <br>
            <div class="messages">
            </div>
            <div class="admin__field field field-attribute_csv  required _required">
                <label class="label admin__field-label" for="attribute_csv">
                    <span>Select File to Import</span>
                </label>
                <div class="admin__field-control control">
                    <input id="attribute_csv" name="attribute_csv" value="" title="Select File to Import" class="attachment required-entry _required" type="file" aria-required="true" />
                </div>
            </div>
        </fieldset>
    </form>
</div>
